### ISSUE TITLE
Sending Lookups is stateful

### ISSUE THREAD

**Issue by PraxTube** [Garic152/homework#10]
Running

```
curl -i localhost:2002/path-with-unknown-hash
```

will give me different results based on how often I ran the above command. For the first time, I will get

```
09:25:46.212323 DEBUG Entering send_reply for connection 6
Handling GET request for /path-with-unknown-hash (0 byte payload)
09:25:46.212356 INFO Node is not responsible, performing lookup or sending 503
09:25:46.212369 WARN Sending 503 Service Unavailable for hash and performing lookup: 58304
09:25:46.212385 INFO Now sending message from node 2002 into dht on socket: 5
09:25:46.212407 INFO Now trying to receive on socket 5
09:25:46.212546 INFO Sending reply: HTTP/1.1 503 Service Unavailable
Retry-After: 5
Content-Length: 0
```

From the first node, and on the second node

```
09:25:46.212431 DEBUG Received UDP data on sock: 5
09:25:46.212472 DEBUG Node not responsible, forwarding to IP: 16777343, PORT: 2002
```

That already seems a bit strange, as the second node thinks it's not responsible, even though it clearly must be? Anyways, curling the same command as above will result in this output.

```
09:25:46.212571 DEBUG Exiting send_reply for connection 6
09:27:40.099852 DEBUG Entering send_reply for connection 6
Handling GET request for /path-with-unknown-hash (0 byte payload)
09:27:40.099874 INFO Node is not responsible, performing lookup or sending 503
09:27:40.099878 INFO Lookup successful for hash: 58304
09:27:40.099882 INFO Sending reply: HTTP/1.1 303 See Other
Location:http://127.0.0.1:2002/path-with-unknown-hash
Content-Length: 0
```

ONLY for node 1, the second node doesn't have any log outputs. Not sure if this is desired behaviour, but I don't understand why it should be.

**Comment by Garic152** [comment]
2002 is not responsible for the hash because it is bigger than the nodes ip
That it gives different results on the second try is also normal because of the DHT lookup behaviour in send_reply
The results are very weird though, because it should have either node1 or node3 in the redirect reply at the end
I was fairly certain that the redirects work after the last commit but apparently there are still some errors

**Comment by PraxTube** [comment]
> 2002 is not responsible for the hash because it is bigger than the nodes ip

Ahh okay I see, so 2001 is responsible then? Why is it sending a lookup, can't it just answer on it's own? Or I guess it's for testing purposes.

> If a node is not responsible and it doesnt yet know which other node is responsible either, it replies with a 503, meaning that the clients browser either manually refreshes or he has to do it himself.
Together with the reply, the node will send a lookup into the dht, hopefully gets back an answer and safes the correct path in typedef struct DHT_History
If the client requests the same node again, it is still not responsible, but now knows the correct path and therefore sends a 303

Okay I think I kinda understand. Will probably throw some more logs at it and figure it out then.

> You can automate retries by using: curl -iL --retry 1 localhost:2002/path-with-unknown-hash

Sweet, thanks.

**Comment by PraxTube** [comment]
> I was fairly certain that the redirects work after the last commit but apparently there are still some errors

The tests are still failing for most look ups on the current branch. Should they pass or are there other known errors that need to be fixed before that?

**Comment by Garic152** [comment]
That's another problem we got right now.
The tests aren't failling due to wrong results but due to timeout errors

**Comment by Garic152** [comment]
```
10:04:08.446255 INFO Node is not responsible, performing lookup or sending 503
10:04:08.446259 INFO Sending 503 Service Unavailable for hash and performing lookup: 1177
10:04:08.446264 INFO Now sending message from node 4711 into dht on socket: 5
10:04:08.446281 INFO Now trying to receive on socket 5
10:04:08.446320 DEBUG Received UDP data on sock: 5
10:04:08.446391 DEBUG Received UDP data on sock: 5
10:04:08.446436 DEBUG Received UDP data on sock: 5
10:04:08.446513 DEBUG Received UDP data on sock: 5
10:04:08.446579 INFO Sending reply: HTTP/1.1 503 Service Unavailable
Retry-After: 5
Content-Length: 0


10:04:08.446595 DEBUG Exiting send_reply for connection 6
10:04:13.447199 DEBUG Entering send_reply for connection 6
Handling GET request for /dynamic/191b023eb6e0090d (0 byte payload)
10:04:13.447221 INFO Node is not responsible, performing lookup or sending 503
10:04:13.447229 INFO Lookup successful for hash: 1177
10:04:13.447237 INFO Sending reply: HTTP/1.1 303 See Other
Location:http://127.0.0.1:4711/dynamic/191b023eb6e0090d
Content-Length: 0


10:04:13.447266 DEBUG Exiting send_reply for connection 6
10:04:13.447707 DEBUG Entering send_reply for connection 6
Handling GET request for /dynamic/191b023eb6e0090d (0 byte payload)
10:04:13.447722 INFO Node is not responsible, performing lookup or sending 503
10:04:13.447729 INFO Lookup successful for hash: 1177
10:04:13.447736 INFO Sending reply: HTTP/1.1 303 See Other
Location:http://127.0.0.1:4711/dynamic/191b023eb6e0090d
Content-Length: 0
```
Those are some of the pytest logs, apparently the tests also fail due to full dht circles which go back to the root node

**Comment by PraxTube** [comment]
So the pytests most likely fail due to #11?
